# Generated by Django 3.1.5 on 2021-01-21 12:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210114_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('address_ar', models.CharField(max_length=200, verbose_name='Address Ar')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=150, verbose_name='Name Ar')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Phone')),
                ('phone2', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Phone')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('logo', models.ImageField(default='/logo/download.jpeg', upload_to='logo/', verbose_name='Logo')),
                ('whatsapp_btn', models.BooleanField(default=True, verbose_name='Whats App')),
            ],
            options={
                'verbose_name': 'Site Info',
            },
        ),
    ]
