# Generated by Django 3.1.5 on 2021-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Customer'), (1, 'Seller')], default=0),
        ),
    ]
