# Generated by Django 3.1.5 on 2021-01-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name ar')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('description_ar', models.CharField(max_length=500, verbose_name='description ar')),
                ('image', models.ImageField(upload_to='category/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name ar')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('description_ar', models.CharField(max_length=500, verbose_name='description ar')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=200, unique=True, verbose_name='sku')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name ar')),
                ('price', models.IntegerField(verbose_name='price')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('description_ar', models.CharField(max_length=500, verbose_name='description ar')),
                ('main_image', models.ImageField(upload_to='product/', verbose_name='main image')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product/', verbose_name='image')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
